const content = (date="______________", name="______") => {
  return (
    <div>
      This Website Developer Agreement (the "<b>Agreement</b>"), dated {date} is entered into by {name} (the "<b>Website Developer</b>"), and Nicolas Salomon (the "Client") <br /><br />
      Whereas, the Website Developer and the Client desire to establish the terms and conditions under which the Website Developer will provide services to the Client, the parties agree as follows:<br /><br />
      <h5>1. Scope of Work.</h5> The Website Developer agrees to perform such consulting, advisory and related services specified on Exhibit A to this Agreement ("Description of Services") <br /><br />
      <h5>2. Term.</h5> This Agreement shall commence from the date this Agreement is signed by both parties and shall continue until {date} (such period, as it may be extended or sooner terminated in accordance with the provisions of Section 4, being referred to as the ("Service Period").<br /><br />
      <h5>3. Payment.</h5> <br />
      <b>a. Service Cost.</b> In consideration of the Service, the Client will pay the Website Developer of $100. <br /><br />
      <b>b. Expenses.</b> The Website Developer shall be responsible for all business expenses incurred by the Website Developer in connection with, or related to, the performance of the services. <br /><br />
      <b>c. Invoices.</b> The Client shall pay to the Website Developer amounts shown on each statement or invoice described in Section 3(a) and 3(b) within seven (7) days after receipt thereof. <br /><br />
      <b>d. Benefits.</b> The Website Developer shall not be entitled to any benefits, coverages or privileges, including, without limitation, health insurance, social security, unemployment, medical or pension payments, made available to employees of the Client. <br /><br />
      <h5>4. Termination.</h5> This Agreement may be terminated prior to the end of the Service Period in the following manner: (a) by either the Website Developer or the Client upon not less than fourteen (14) days prior written notice to the other party; (b) by the non-breaching party, upon twenty-four (24) hours prior written notice to the breaching party if one party has materially breached this Agreement; or (c) at any time upon the mutual written consent of the parties hereto. In the event of termination, the Website Developer shall be entitled to payments for services performed that have not been previously paid and, subject to the limitations in Section 3.2, for expenses paid or incurred prior to the effective date of termination that have not been previously paid. Such payment shall constitute full settlement of any and all claims of the Website Developer of every description against the Client. In the event that the Client’s payment to the Website Developer exceeds the amount of services performed and (subject to the limitations in Section 3.2) for expenses paid or incurred prior to the effective date of termination, then the Website Developer will immediately refund the excess amount to the Client. Such refund shall constitute full settlement of any and all claims of the Client of every description against the Website Developer <br /><br />
      <h5>5. Cooperation. </h5>The Website Developer shall use Website Developer's best efforts in the performance of Website Developer's obligations under this Agreement. The Client shall provide such access to its information and property as may be reasonably required in order to permit the Website Developer to perform Website Developer's obligations hereunder. The Website Developer shall cooperate with the Client’s personnel, shall not interfere with the conduct of the Client’s business and shall observe all rules, regulations and security requirements of the Client concerning the safety of persons and property. <br /><br />
      <h5>6. Proprietary Information and Inventions.</h5> <br />
      <b>a. Proprietary Information.</b> <br />
      1. The Website Developer acknowledges that Website Developer’s relationship with the Client is one of high trust and confidence and that in the course of Website Developer's service to the Client, Website Developer will have access to and contact with Proprietary Information. The Website Developer will not disclose any Proprietary Information to any person or entity other than employees of the Client or use the same for any purposes (other than in the performance of the services) without written approval by an officer of the Client, either during or after the Consultation Period, unless and until such Proprietary Information has become public knowledge without fault by the Website Developer. <br /><br />
      2. For purposes of this Agreement, Proprietary Information shall mean, by way of illustration and not limitation, all information, whether or not in writing, whether or not patentable and whether or not copyrightable, of a private, secret or confidential nature, owned, possessed or used by the Client, concerning the Client’s business, business relationships or financial affairs, including, without limitation, any Invention, formula, vendor information, customer information, apparatus, equipment, trade secret, process, research, report, technical or research data, clinical data, know-how, computer program, software, software documentation, hardware design, technology, product, processes, methods, techniques, formulas, compounds, projects, developments, marketing or business plan, forecast, unpublished financial statement, budget, license, price, cost, customer, supplier or personnel information or employee list that is communicated to, learned of, developed or otherwise acquired by the Website Developer in the course of Website Developer's service as a website developer to the Client. <br /><br />
      3. The Website Developer’s obligations under this Section 6 shall not apply to any information that (i) is or becomes known to the general public under circumstances involving no breach by the Website Developer or others of the terms of this Section 6, (ii) is generally disclosed to third parties by the Client without restriction on such third parties, or (iii) is approved for release by written authorization of an officer of the Client. <br /><br />
      4. The Website Developer agrees that all files, documents, letters, memoranda, reports, records, data sketches, drawings, models, laboratory notebooks, program listings, computer equipment or devices, computer programs or other written, photographic, or other tangible material containing Proprietary Information, whether created by the Website Developer or others, which shall come into Website Developer's custody or possession, shall be and are the exclusive property of the Client to be used by the Website Developer <br /><br />
      5. The Website Developer agrees that Website Developer’s obligation not to disclose or to use information and materials of the types set forth in paragraphs (2) and (4) above, and Website Developer's obligation to return materials and tangible property set forth in paragraph (4) above extends to such types of information, materials and tangible property of customers of the Client or suppliers to the Client or other third parties who may have disclosed or entrusted the same to the Client or to the Website Developer. <br /><br />
      6. The Website Developer acknowledges that the Client from time to time may have agreements with other persons or with the United States Government, or agencies thereof, that impose obligations or restrictions on the Client regarding inventions made during the course of work under such agreements or regarding the confidential nature of such work. The Website Developer agrees to be bound by all such obligations and restrictions that are known to Website Developer and to take all action necessary to discharge the obligations of the Client under such agreements. <br /><br />
      <b>b. Inventions.</b> <br />
      1. All inventions, ideas, creations, discoveries, computer programs, works of authorship, data, developments, technology, designs, innovations and improvements (whether or not patentable and whether or not copyrightable) which are made, conceived, reduced to practice, created, written, designed or developed by the Website Developer, solely or jointly with others or under Website Developer's direction and whether during normal business hours or otherwise, (i) during the Consultation Period if related to the business of the Client or (ii) after the Consultation Period if resulting or directly derived from Proprietary Information (as defined below) (collectively under clauses (i) and (ii), "Inventions"), shall be the sole property of the Client. The Website Developer hereby assigns to the Client all Inventions and any and all related patents, copyrights, trademarks, trade names, and other industrial and intellectual property rights and applications therefore, in the United States and elsewhere and appoints any officer of the Client as Website Developer's duly authorized attorney to execute, file, prosecute and protect the same before any government agency, court or authority. However, this paragraph shall not apply to Inventions which do not relate to the business or research and development conducted or planned to be conducted by the Client at the time such Invention is created, made, conceived or reduced to practice and which are made and conceived by the Website Developer not during normal working hours, not on the Client’s premises and not using the Client’s tools, devices, equipment or Proprietary Information. The Website Developer further acknowledges that each original work of authorship which is made by the Website Developer (solely or jointly with others) within the scope of the Agreement and which is protectable by copyright is a "work made for hire," as that term is defined in the United States Copyright Act. <br /><br />
      2. Upon the request of the Client and at the Client’s expense, the Website Developer shall execute such further assignments, documents and other instruments as may be necessary or desirable to fully and completely assign all Inventions to the Client and to assist the Client in applying for, obtaining and enforcing patents or copyrights or other rights in the United States and in any foreign country with respect to any Invention. The Website Developer also hereby waives all claims to moral rights in any Inventions. <br /><br />
      3. The Website Developer shall promptly disclose to the Client all Inventions and will maintain adequate and current written records (in the form of notes, sketches, drawings and as may be specified by the Client) to document the conception and/or first actual reduction to practice of any Invention. Such written records shall be available to and remain the sole property of the Client at all times. <br /><br />
      4. Notwithstanding the foregoing in this Section 6(b), the ownership and use of the Inventions that are assigned to the Client in Section 6(b)(i) (the "Assigned Inventions") shall be limited as set forth in 6(c). <br /><br />
      <b>c. Use of Work Product License.</b> Once the Website Developer delivers the work product to the Client, the Website Developer does not have any rights to it, except those that the Client explicitly grants the Website Developer as written here. The Client grants permission for the Website Developer to display all aspects of their work, including but not limited to any sketches, work-in-progress material, and final deliverable content, so long as it is for showcasing the work and not for any other purpose. The client gives the Website Developer permission to show this work as part of portfolios, websites, galleries, and other media. The Client does not grant permission to use the work product for sale or for any other commercial use. The Client cannot revoke this license, even if the Contract ends or is terminated. <br /><br />
      IN WITNESS WHEREOF, the parties hereto have executed this WEBSITE DEVELOPER AGREEMENT<br /><br />
    </div>
  );
};

export default content;